import styled from 'styled-components';

export const InputArquivo = styled.input`
    display: none;
`;

export const dadosCursos = {
    "Curso": {
        periodos: ["Período"],
        disciplinas: [],
    },
    "CC": {
        periodos: [
          "Período",
          "1º Período",
          "2º Período",
          "3º Período",
          "4º Período",
          "5º Período",
          "6º Período",
          "7º Período",
          "Computação Visual",
          "Sistemas Inteligentes",
          "Sistemas de Computação",
          "Sistemas de Informação",
        ],
        disciplinas: {
          "1º Período": ["P1", "LÓG", "CSÉ", "MD", "CDI"],
          "2º Período": ["ED", "BD", "OAC", "GA"],
          "3º Período": ["REDC", "TG", "PROB", "ÁLG"],
          "4º Período": ["P2", "P3", "PAA", "TCOMP"],
          "5º Período": ["SO", "COMPI", "IA", "CG"],
          "6º Período": ["PDS"],
          "7º Período": ["MET", "ND"],
          "Computação Visual": ["C3", "AM", "RNAP", "PDI", "VISC"],
          "Sistemas Inteligentes": ["C3", "AM", "RNAP", "CEVO", "CD"],
          "Sistemas de Computação": ["C3", "SDG", "FPGA", "SE", "MICR"],
          "Sistemas de Informação": ["CLP", "SDI", "IHM", "GP", "SEG"],
        },
        assuntos: {
          "P1": ["Sintaxe Básica", "Estruturas de Controle", "Funções", "Tipos de Dados", "Arrays", "Ponteiros", "Estruturas e Uniões", "Entrada e Saída", "Alocação Dinâmica de Memória", "Manipulação de Strings", "Arquivos", "Bibliotecas Padrão", "Práticas de Codificação", "Depuração", "Projetos Práticos", "Outros", "AB1", "AB2", "Reavaliação"],
          "LÓG": ["Lógica Proposicional", "Lógica de Primeira Ordem", "Tabelas-Verdade", "Leis da Lógica", "Demonstrações Lógicas", "Álgebra Booleana", "Sintaxe e Semântica Lógica", "Raciocínio Dedutivo e Indutivo", "Resolução de Problemas Lógicos", "Lógica de Programação", "Teorema de Gödel", "Lógica Temporal", "Lógica Modal", "Linguagens Formais", "Aplicações em Inteligência Artificial", "Outros", "AB1", "AB2", "Reavaliação"],
          "CSÉ": ["Privacidade de Dados", "Ética na Inteligência Artificial (IA)", "Vigilância Digital", "Cibersegurança e Hacking Ético", "Responsabilidade em TI", "Desigualdades Digitais", "Neutralidade da Rede", "Ética em Big Data", "Propriedade Intelectual e Direitos Autorais", "Ética em Pesquisa em Computação", "Inteligência Artificial e Emprego", "Ética em Jogos e Entretenimento Digital", "Ética em Redes Sociais", "Acesso Universal à Tecnologia", "Ética no Desenvolvimento de Software", "Outros", "AB1", "AB2", "Reavaliação"],
          "MD": ["Teoria dos Conjuntos", "Relações", "Funções", "Álgebra Booleana", "Teoria dos Números", "Relações", "Congruência Linear", "Métodos de provas", "Teorema Chinês do Resto", "Teorema de Fermat", "Introdução a Criptografia", "Teoria dos Conjuntos Finitos", "Álgebra de Boole e Circuitos Lógicos", "Teoria dos Números Criptográficos", "Probabilidade Discreta", "Outros", "AB1", "AB2", "Reavaliação"],
          "CDI": ["Limites e Continuidade", "Derivadas e Regras de derivação", "Aplicações de Derivada", "Teorema do Valor médio e Rolle", "Regra de L'Hôpital", "Aplicações", "Definição da Integral Definida", "Propriedades da Integral Definida", "Teorema Fundamental do Cálculo", "Regras de Integração", "Aplicações da Integral Definida", "Cálculo de Áreas e Volumes", "Integral Imprópria", "Séries e Sequências", "Equações Diferenciais", "Outros", "AB1", "AB2", "Reavaliação"],
          "ED": ["Arrays", "Listas Ligadas", "Pilhas (Stacks)", "Filas (Queues)", "Árvores", "Árvores Binárias", "Árvores Balanceadas", "Grafos", "Tabelas Hash", "Listas Duplamente Ligadas", "Heaps", "Grafos Direcionados", "Fila de Prioridade", "Árvores B", "Grafos Ponderados", "Outros", "AB1", "AB2", "Reavaliação"],
          "BD": ["Modelo de Dados", "SQL (Structured Query Language)", "Sistemas de Gerenciamento de Banco de Dados (DBMS)", "Normalização", "Chave Primária e Chave Estrangeira", "Índices", "Transações", "NoSQL Databases", "Replicação de Dados", "Sharding", "Banco de Dados em Memória", "Backup e Recuperação", "Segurança de Banco de Dados", "Modelagem de Dados", "Big Data", "Outros", "AB1", "AB2", "Reavaliação"],
          "OAC": ["Arquitetura de Software", "Padrões de Projeto (Design Patterns)", "Arquitetura em Camadas", "Model-View-Controller (MVC)", "Microsserviços", "Arquitetura Orientada a Serviços (SOA)", "Arquitetura de Pipeline", "Padrões de Comunicação", "Injeção de Dependência (DI)", "Arquitetura Monolítica", "Arquitetura de Software Escalável", "Refatoração de Software", "Padrões de Arquitetura de Segurança", "Arquitetura Orientada a Eventos (EDA)", "Arquitetura de Software Distribuído", "Outros", "AB1", "AB2", "Reavaliação"],
          "GA": ["Sistemas de Coordenadas", "Pontos, Linhas e Planos", "Distância e Comprimento de Segmentos de Reta", "Equações de Retas", "Ângulos e Inclinações", "Circunferências", "Parábolas, Elipses e Hipérboles", "Translação e Rotação", "Sistemas de Equações Lineares", "Vetores no Plano e no Espaço", "Produto Escalar e Produto Vetorial", "Plano Cartesiano Tridimensional", "Retas e Planos no Espaço", "Superfícies de Revolução e Cilindros", "Coordenadas Polares e Cilíndricas", "Coordenadas Esféricas e Cônicas", "Outros", "AB1", "AB2", "Reavaliação"],
          "REDC": ["Topologias de Rede", "Protocolos de Rede", "Modelo OSI", "Arquiteturas de Rede", "Endereçamento IP", "Roteamento", "Switches e Roteadores", "Protocolos de Roteamento", "Redes Sem Fio", "Segurança de Rede", "Virtualização de Rede", "Redes de Área Local (LAN)", "Redes de Área Ampla (WAN)", "Redes de Data Center", "Monitoramento e Gerenciamento de Rede", "Outros", "AB1", "AB2", "Reavaliação"],
          "TG": ["Grafos e Subgrafos", "Grafos Dirigidos", "Grafos Não-dirigidos", "Grafos Ponderados", "Grafos Conexos e Desconexos", "Árvores e Florestas", "Grafos Bipartidos", "Caminhos e Ciclos", "Grafos Eulerianos e Hamiltonianos", "Matriz de Adjacência e Lista de Adjacência", "Algoritmos de Busca", "Algoritmos de Caminho Mínimo", "Algoritmos de Fluxo Máximo", "Grafos Planos", "Aplicações em Redes Sociais", "Outros", "AB1", "AB2", "Reavaliação"], 
          "PROB": ["Probabilidade", "Variáveis Aleatórias", "Distribuição de Probabilidade", "Distribuições de Probabilidade Comuns", "Teorema do Limite Central", "Amostragem e Estimação", "Intervalos de Confiança", "Testes de Hipóteses", "Correlação e Regressão", "Estatísticas Descritivas", "Amostragem Aleatória Simples", "Experimentos Aleatórios", "Análise de Séries Temporais", "Estatística Bayesiana", "Aplicações em Ciência e Indústria", "Outros", "AB1", "AB2", "Reavaliação"], 
          "ÁLG": ["Vetores", "Espaços Vetoriais", "Operações Vetoriais", "Independência Linear", "Base e Dimensão", "Transformações Lineares", "Matrizes", "Espaço Nulo e Espaço Coluna", "Sistemas de Equações Lineares", "Determinantes", "Autovalores e Autovetores", "Diagonalização", "Espaços Ortogonais", "Decomposição QR", "Álgebra Linear Numérica", "Outros", "AB1", "AB2", "Reavaliação"], 
          "P2": ["Padrões de Projeto (Design Patterns)", "Arquiteturas de Software", "Desenvolvimento Orientado a Objetos (OOD)", "Testes de Software", "Gerenciamento de Configuração", "Documentação de Software", "Desenvolvimento Ágil", "Controle de Qualidade de Código", "Integração Contínua e Desdobramento Contínuo (CI/CD)", "Gestão de Equipe de Desenvolvimento", "Desenvolvimento de Interfaces de Programação de Aplicativos (APIs)", "Desenvolvimento de Aplicações Web e Móveis", "Segurança de Software", "Usabilidade e Experiência do Usuário (UX/UI)", "Empacotamento e Distribuição de Software", "Outros", "AB1", "AB2", "Reavaliação"],
          "P3": ["Frameworks de Desenvolvimento Web", "Desenvolvimento de Aplicações de Uma Página (SPA)", "APIs RESTful", "Gerenciamento de Estado no Front-End", "Desenvolvimento de Aplicativos Web Progressivos (PWAs)", "Segurança em Aplicações Web", "Banco de Dados no Back-End", "Autenticação e Autorização", "Desenvolvimento Full-Stack", "Arquitetura de Microsserviços", "Desenvolvimento Responsivo", "Testes Automatizados", "Hospedagem e Implantação", "Controle de Versão Avançado", "Desenvolvimento de Aplicações Web em Tempo Real", "Outros", "AB1", "AB2", "Reavaliação"],
          "PAA": ["Análise de Complexidade", "Algoritmos de Ordenação", "Algoritmos de Busca", "Algoritmos de Grafos", "Algoritmos de Programação Dinâmica", "Algoritmos de Fluxo Máximo", "Algoritmos de Geometria Computacional", "Algoritmos Greedy", "Algoritmos de Correspondência", "Algoritmos de Compressão de Dados", "Algoritmos de Aproximação", "Algoritmos em Cadeias de Caracteres", "Algoritmos Distribuídos", "Algoritmos Paralelos", "Problemas NP-Completos e Teoria da Complexidade", "Outros", "AB1", "AB2", "Reavaliação"],
          "TCOMP": ["Autômatos", "Linguagens Formais", "Hierarquia de Chomsky", "Problemas de Decisão", "Complexidade Computacional", "Teorema de Church-Turing", "Redutibilidade", "Máquinas Não-determinísticas", "Teoria da Computabilidade", "Teoria da Incompletude de Gödel", "Teoria da Informação", "Teoria da Prova", "Autômatos Celulares", "Teoria dos Jogos Computacionais", "Lógica Matemática", "Outros", "AB1", "AB2", "Reavaliação"],
          "SO": ["Funções Básicas do SO", "Multi tarefa", "Multi Processamento", "Interface com o Usuário", "Gerenciamento de Arquivos", "Segurança e Controle de Acesso", "Sistemas de Arquivos", "Gestão de Memória", "Sistemas de Arquivos Distribuídos", "Rede e Comunicação", "Inicialização do Sistema", "Desempenho e Otimização", "Manutenção e Atualizações", "Sistemas Operacionais Móveis", "Virtualização", "Outros", "AB1", "AB2", "Reavaliação"],
          "COMPI": ["Fases do Compilador", "Análise Léxica", "Análise Sintática", "Análise Semântica", "Tabela de Símbolos", "Geração de Código Intermediário", "Otimização de Código", "Geração de Código de Máquina", "Compiladores vs. Interpretadores", "Linguagens de Programação", "Bibliotecas e APIs", "Depuração", "Compiladores Just-in-Time (JIT)", "Compiladores de Linguagem de Montagem", "Compiladores de Alto Desempenho", "Outros", "AB1", "AB2", "Reavaliação"],
          "IA": ["Aprendizado de Máquina (Machine Learning)", "Redes Neurais Artificiais", "Processamento de Linguagem Natural (PLN)", "Visão Computacional", "Robótica Inteligente", "Agentes Inteligentes", "Aprendizado Profundo (Deep Learning)", "Algoritmos de IA", "Ética em IA", "IA e Medicina", "IA e Automóveis Autônomos", "IA na Indústria", "IA na Educação", "IA na Finança", "Futuro da IA", "Outros", "AB1", "AB2", "Reavaliação"],
          "CG": ["Rasterização e Vetorização", "Modelagem 3D", "Renderização", "Texturização", "Animação", "Realidade Virtual (VR) e Realidade Aumentada (AR)", "Gráficos de Jogos", "Simulação", "Visualização de Dados", "Edição de Imagens", "Técnicas de Pintura Digital", "Computação Gráfica em Medicina", "Computação Gráfica em Design Industrial", "Computação Gráfica em Animação por Computador (CGI)", "Tendências em Computação Gráfica", "Outros", "AB1", "AB2", "Reavaliação"],
          "PDS": ["Requisitos de Software", "Arquitetura de Software", "Modelagem de Dados", "Linguagem de Programação", "Design de Interface de Usuário (UI/UX)", "Desenvolvimento de Código", "Teste de Software", "Controle de Versão e Gerenciamento de Código", "Ciclo de Desenvolvimento de Software", "Documentação de Software", "Segurança de Software", "Testes de Aceitação do Usuário (UAT)", "Implantação e Integração", "Manutenção de Software", "Gerenciamento de Projeto de Software", "Outros", "AB1", "AB2", "Reavaliação"],
          "MET": ["Formulação do Problema de Pesquisa", "Revisão da Literatura", "Definição de Objetivos e Hipóteses", "Seleção de Método de Pesquisa", "Coleta de Dados", "Amostragem", "Procedimentos de Coleta de Dados", "Análise de Dados", "Validade e Confiabilidade", "Interpretação dos Resultados", "Discussão", "Conclusões", "Limitações do Estudo", "Ética na Pesquisa", "Divulgação e Publicação", "Outros", "AB1", "AB2", "Reavaliação"],
          "ND": ["Regras e Leis", "Justiça", "Igualdade perante a Lei", "Presunção de Inocência", "Devido Processo Legal", "Direitos Humanos", "Responsabilidade Civil e Criminal", "Contratos", "Propriedade", "Jurisprudência", "Órgãos Jurídicos", "Advogados e Juízes", "Princípio do Contraditório", "Prescrição", "Legislação e Poder Legislativo", "Outros", "AB1", "AB2", "Reavaliação"],
          "C3": ["Limites e Continuidade", "Derivadas e Regras de derivação", "Aplicações de Derivada", "Teorema do Valor médio e Rolle", "Regra de L'Hôpital", "Aplicações", "Definição da Integral Definida", "Propriedades da Integral Definida", "Teorema Fundamental do Cálculo", "Regras de Integração", "Aplicações da Integral Definida", "Cálculo de Áreas e Volumes", "Integral Imprópria", "Séries e Sequências", "Equações Diferenciais", "Outros", "AB1", "AB2", "Reavaliação"],
          "AM": [
            "Introdução ao Aprendizado de Máquina",
            "Pré-processamento de Dados",
            "Aprendizado Supervisionado",
            "Algoritmos de Classificação",
            "Algoritmos de Regressão",
            "Aprendizado Não Supervisionado",
            "Algoritmos de Agrupamento",
            "Redução de Dimensionalidade",
            "Aprendizado por Reforço",
            "Redes Neurais Artificiais",
            "Frameworks de Aprendizado de Máquina",
            "Avaliação de Modelos",
            "Seleção de Recursos",
            "Ética e Viés em Aprendizado de Máquina",
            "Aplicações do Aprendizado de Máquina"
        ],
          "RNAP": [
            "Introdução às Redes Neurais",
            "Perceptrons e Redes Neurais Feedforward",
            "Funções de Ativação",
            "Treinamento de Redes Neurais",
            "Redes Neurais Convolucionais (CNNs)",
            "Redes Neurais Recorrentes (RNNs)",
            "Arquiteturas de RNN",
            "Redes Neurais Profundas",
            "Transfer Learning",
            "Redes Generativas Adversariais (GANs)",
            "Autoencoders",
            "Processamento de Linguagem Natural (NLP)",
            "Redes Neurais Recorrentes para NLP",
            "Frameworks de Deep Learning",
            "Ética e Interpretabilidade"
        ],
          "PDI": [
            "Fundamentos de Processamento de Imagem",
            "Pré-processamento de Imagem",
            "Transformações Geométricas",
            "Segmentação de Imagem",
            "Extração de Características",
            "Morfologia Matemática",
            "Filtros de Imagem",
            "Correspondência de Imagens",
            "Transformada de Fourier e Espacial",
            "Detecção de Borda",
            "Reconhecimento de Padrões em Imagens",
            "Processamento de Imagem em Cores",
            "Processamento de Imagem em Tempo Real",
            "Visão Computacional",
            "Aplicações de Processamento de Imagem"
        ],
          "VISC": [
            "Fundamentos de Processamento de Imagem",
            "Pré-processamento de Imagem",
            "Detecção de Borda",
            "Segmentação de Imagem",
            "Extração de Características",
            "Correspondência de Características",
            "Transformação Geométrica",
            "Rastreamento de Objetos",
            "Visão Estéreo e Disparidade",
            "Classificação de Objetos",
            "Detecção de Objetos",
            "Redes Neurais Convolutivas (CNNs)",
            "Visão Computacional 3D",
            "Aplicações de Visão Computacional",
            "Desafios Éticos em Visão Computacional"
        ],
          "SDG": ["Álgebra de Boole", "Portas Lógicas", "Sistemas de Numeração", "Circuitos Combinacionais", "Multiplexadores e Demultiplexadores", "Decodificadores e Codificadores", "Flip-Flops e Registradores", "Contadores e Temporizadores", "Sistemas de Lógica Programável", "Memória Digital", "Sistemas de Clock e Sincronização", "Projeto de Circuitos Digitais", "Arquitetura de Processadores", "Microcontroladores", "Sistemas Digitais em FPGA", "Outros", "AB1", "AB2", "Reavaliação"],
          "FPGA": ["Introdução aos FPGAs", "Linguagens de Descrição de Hardware (HDLs)", "Arquitetura de FPGA", "Síntese Lógica", "Implementação e Roteamento", "Circuitos Lógicos Programáveis", "IP Cores (Intellectual Property Cores)", "Design Reconfigurável", "Processadores Embutidos em FPGAs", "Interfaceamento com Periféricos", "Sistemas Embarcados com FPGAs", "FPGA em Aplicações de Comunicação", "FPGA em Processamento de Sinal", "FPGA em Computação de Alto Desempenho (HPC)", "Tendências em FPGA", "Outros", "AB1", "AB2", "Reavaliação"],
          "SE": ["Introdução a Sistemas Embarcados", "Microcontroladores", "Arquitetura de Computadores Embarcados", "Programação de Baixo Nível", "Sistemas Operacionais Embarcados", "Periféricos e Interfaces", "Comunicação sem Fio", "Economia de Energia", "Desenvolvimento de Firmware", "Segurança em Sistemas Embarcados", "Depuração e Testes", "Design de Sistemas Embarcados", "Sistemas Embarcados em Tempo Real", "Sistemas Embarcados em Automóveis", "Tendências em Sistemas Embarcados", "Outros", "AB1", "AB2", "Reavaliação"],
          "MICR": ["Introdução a Microcontroladores", "Arquitetura de Microcontroladores", "Programação de Microcontroladores", "Periféricos de Microcontroladores", "Comunicação Serial", "Interrupções e Temporização", "Memória de Programa e Dados", "Conversão Analógico-Digital (ADC)", "PWM (Modulação por largura de pulso)", "Interface com Sensores", "Sistemas de Controle Embarcados", "Microcontroladores em Eletrônica de Consumo", "Aplicações Automotivas", "Microcontroladores em Dispositivos Médicos", "Desenvolvimento de Projetos com Microcontroladores", "Outros", "AB1", "AB2", "Reavaliação"],
          "CLP": ["Introdução às Linguagens de Programação", "Sintaxe e Semântica", "Tipos de Dados", "Variáveis e Constantes", "Estruturas de Controle", "Funções e Procedimentos", "Escopo de Variáveis", "Recursão", "Programação Orientada a Objetos", "Manipulação de Exceções", "Programação Funcional", "Paradigmas de Linguagens de Programação", "Compilação vs. Interpretação", "Gerenciamento de Memória", "Linguagens de Programação Populares", "Outros", "AB1", "AB2", "Reavaliação"],
          "SDI": ["Álgebra de Boole", "Portas Lógicas", "Sistemas de Numeração", "Circuitos Combinacionais", "Multiplexadores e Demultiplexadores", "Decodificadores e Codificadores", "Flip-Flops e Registradores", "Contadores e Temporizadores", "Sistemas de Lógica Programável", "Memória Digital", "Sistemas de Clock e Sincronização", "Projeto de Circuitos Digitais", "Arquitetura de Processadores", "Microcontroladores", "Sistemas Digitais em FPGA", "Outros", "AB1", "AB2", "Reavaliação"],
          "IHM": ["Fundamentos da Segurança de Sistemas", "Políticas de Segurança", "Criptografia", "Autenticação e Autorização", "Firewalls e IDS/IPS", "Vulnerabilidades e Exploits", "Gestão de Identidade e Acesso", "Segurança de Redes", "Segurança em Sistemas Operacionais", "Segurança em Aplicações Web", "Segurança em Dispositivos Móveis", "Gestão de Incidentes de Segurança", "Conformidade e Regulamentações", "Segurança em Nuvem", "Tendências em Segurança", "Outros", "AB1", "AB2", "Reavaliação"],
          "GP": ["Introdução à Ciência de Dados", "Coleta de Dados", "Limpeza e Pré-processamento de Dados", "Análise Exploratória de Dados (EDA)", "Estatística", "Aprendizado de Máquina (Machine Learning)", "Big Data", "Processamento de Linguagem Natural (NLP)", "Aprendizado Profundo (Deep Learning)", "Mineração de Dados", "Visualização de Dados", "Modelagem Preditiva", "Ética e Privacidade de Dados", "Deploy de Modelos", "Casos de Uso em Ciência de Dados", "Outros", "AB1", "AB2", "Reavaliação"],
          "SEG": ["Limites e Continuidade", "Derivadas e Regras de derivação", "Aplicações de Derivada", "Teorema do Valor médio e Rolle", "Regra de L'Hôpital", "Aplicações", "Definição da Integral Definida", "Propriedades da Integral Definida", "Teorema Fundamental do Cálculo", "Regras de Integração", "Aplicações da Integral Definida", "Cálculo de Áreas e Volumes", "Integral Imprópria", "Séries e Sequências", "Equações Diferenciais", "Outros", "AB1", "AB2", "Reavaliação"],
          "CD": ["Introdução à Ciência de Dados", "Coleta de Dados", "Limpeza e Pré-processamento de Dados", "Análise Exploratória de Dados (EDA)", "Estatística", "Aprendizado de Máquina (Machine Learning)", "Big Data", "Processamento de Linguagem Natural (NLP)", "Aprendizado Profundo (Deep Learning)", "Mineração de Dados", "Visualização de Dados", "Modelagem Preditiva", "Ética e Privacidade de Dados", "Deploy de Modelos", "Casos de Uso em Ciência de Dados", "Outros", "AB1", "AB2", "Reavaliação"],
        }

    },
    "EC": {
        periodos: [
          "Período",
          "1º Período",
          "2º Período",
          "3º Período",
          "4º Período",
          "5º Período",
          "6º Período",
          "7º Período",
          "8º Período",
          "Eletivas",
          "Eletivas 2",
        ],
        disciplinas: {
          "1º Período": ["INGL", "P1", "MD", "C1", "GA", "IENG"],
          "2º Período": ["LÓG", "ED", "FÍSI", "CÁL2", "ÁLG", "CIDI", "DESE"],
          "3º Período": ["LFAU", "PSOF", "FÍS2", "C3", "MET", "SDG", "QUTE"],
          "4º Período": ["PROB", "ENGS", "CÁL4", "VACO", "OAC", "FÍEX"],
          "5º Período": ["PAA", "CIEL", "REDC", "SISE", "IA", "SO", "TG"],
          "6º Período": ["PRCO", "ELET", "METN", "SICO", "CSÉ", "EMPE", "FETR"],
          "7º Período": ["BD", "ND", "SICO2", "MICR", "INEL", "PDIS"],
          "8º Período": ["CG", "SE", "SDI", "AUIN", "ROBÓ", "MÉSO"],
          "Eletivas": ["CLP", "SEVE", "COMPI", "PRLP", "GP", "LAPR", "FLIB", "DBON", "TECÉ"],
          "Eletivas 2": ["LAED", "LAEL", "LACE", "REPE", "TSD1", "TSD2", "ITIN", "IA2", "DCQC"],
        },
        assuntos: {
          "INGL":[
            "Programação em Inglês",
            "Algoritmos e Estruturas de Dados",
            "Redes de Computadores",
            "Banco de Dados",
            "Sistemas Operacionais",
            "Desenvolvimento Web",
            "Engenharia de Software",
            "Inteligência Artificial e Aprendizado de Máquina",
            "Segurança da Informação",
            "Internet das Coisas (IoT)",
            "Arquitetura de Computadores",
            "Desenvolvimento de Aplicativos Móveis",
            "Engenharia de Software Embarcado",
            "Cloud Computing",
            "Robótica"
        ],
          "TSD1":[
            "Modelos de Computação Distribuída",
            "Comunicação em Redes Distribuídas",
            "Coordenação Distribuída",
            "Consenso Distribuído",
            "Distribuição de Dados",
            "Detecção de Falhas",
            "Tolerância a Falhas",
            "Algoritmos de Roteamento",
            "Algoritmos de Distribuição de Recursos",
            "Segurança em Sistemas Distribuídos",
            "Sistemas de Mensagens Assíncronas",
            "Protocolos de Consistência",
            "Virtualização e Contêineres",
            "Escalabilidade e Desempenho",
            "Aplicações de Algoritmos Distribuídos"
        ],
          "TSD2":[
            "Escalonamento de Transações Distribuídas",
            "Distribuição de Conteúdo em Redes Peer-to-Peer (P2P)",
            "Computação em Nuvem e Orquestração de Contêineres",
            "Sistemas de Armazenamento Distribuído",
            "Bases de Dados Distribuídas NoSQL",
            "Tolerância a Partições de Rede",
            "Consistência em Escala",
            "Distribuição de Dados Geograficamente Distribuídos",
            "Sistemas de Blockchain e Contratos Inteligentes",
            "Redes de Sensores sem Fio",
            "Sistemas Distribuídos em Tempo Real",
            "Aplicações de Machine Learning Distribuído",
            "Sistemas de Rastreamento e Gerenciamento de Recursos",
            "Sistemas de Recomendação Distribuídos",
            "Aplicações em IoT (Internet das Coisas)"
        ],
          "P1": ["Sintaxe Básica", "Estruturas de Controle", "Funções", "Tipos de Dados", "Arrays", "Ponteiros", "Estruturas e Uniões", "Entrada e Saída", "Alocação Dinâmica de Memória", "Manipulação de Strings", "Arquivos", "Bibliotecas Padrão", "Práticas de Codificação", "Depuração", "Projetos Práticos", "Outros", "AB1", "AB2", "Reavaliação"],
          "MD": ["Teoria dos Conjuntos", "Relações", "Funções", "Álgebra Booleana", "Teoria dos Números", "Relações", "Congruência Linear", "Métodos de provas", "Teorema Chinês do Resto", "Teorema de Fermat", "Introdução a Criptografia", "Teoria dos Conjuntos Finitos", "Álgebra de Boole e Circuitos Lógicos", "Teoria dos Números Criptográficos", "Probabilidade Discreta", "Outros", "AB1", "AB2", "Reavaliação"],
          "C1":[
            "Funções e Gráficos",
            "Limites e Continuidade",
            "Derivadas",
            "Aplicações de Derivadas",
            "Integrais Definidas",
            "Técnicas de Integração",
            "Aplicações de Integrais",
            "Funções Trigonométricas",
            "Sequências e Séries",
            "Teorema do Valor Médio e Teorema do Valor Extremo",
            "Integração Numérica",
            "Equações Diferenciais",
            "Modelagem Matemática",
            "Aplicações em Engenharia de Computação",
            "Laboratórios e Exercícios Práticos"
        ],
          "GA":["Sistemas de Coordenadas", "Pontos, Linhas e Planos", "Distância e Comprimento de Segmentos de Reta", "Equações de Retas", "Ângulos e Inclinações", "Circunferências", "Parábolas, Elipses e Hipérboles", "Translação e Rotação", "Sistemas de Equações Lineares", "Vetores no Plano e no Espaço", "Produto Escalar e Produto Vetorial", "Plano Cartesiano Tridimensional", "Retas e Planos no Espaço", "Superfícies de Revolução e Cilindros", "Coordenadas Polares e Cilíndricas", "Coordenadas Esféricas e Cônicas", "Outros", "AB1", "AB2", "Reavaliação"],
          "IENG":[
            "História da Computação",
            "Arquitetura de Computadores",
            "Fundamentos de Programação",
            "Sistemas Operacionais",
            "Redes de Computadores",
            "Algoritmos e Estruturas de Dados",
            "Engenharia de Software",
            "Inteligência Artificial",
            "Segurança da Informação",
            "Desenvolvimento de Projetos em Equipe",
            "Ética e Responsabilidade Social",
            "Tendências Tecnológicas",
            "Empreendedorismo em Tecnologia",
            "Robótica",
            "Aplicações Práticas"
        ],
        "LÓG": ["Lógica Proposicional", "Lógica de Primeira Ordem", "Tabelas-Verdade", "Leis da Lógica", "Demonstrações Lógicas", "Álgebra Booleana", "Sintaxe e Semântica Lógica", "Raciocínio Dedutivo e Indutivo", "Resolução de Problemas Lógicos", "Lógica de Programação", "Teorema de Gödel", "Lógica Temporal", "Lógica Modal", "Linguagens Formais", "Aplicações em Inteligência Artificial", "Outros", "AB1", "AB2", "Reavaliação"],
        "ED": ["Arrays", "Listas Ligadas", "Pilhas (Stacks)", "Filas (Queues)", "Árvores", "Árvores Binárias", "Árvores Balanceadas", "Grafos", "Tabelas Hash", "Listas Duplamente Ligadas", "Heaps", "Grafos Direcionados", "Fila de Prioridade", "Árvores B", "Grafos Ponderados", "Outros", "AB1", "AB2", "Reavaliação"],
          "FÍSI":[
            "Cinemática",
            "Dinâmica",
            "Leis de Conservação",
            "Trabalho e Energia",
            "Impulso e Colisões",
            "Rotação e Momento Angular",
            "Gravitação Universal",
            "Fluidos",
            "Ondas e Som",
            "Óptica",
            "Eletricidade e Magnetismo",
            "Circuitos Elétricos",
            "Campo Elétrico e Campo Magnético",
            "Eletromagnetismo",
            "Termodinâmica"
        ],
          "CÁL2":[
            "Integração Definida",
            "Técnicas de Integração",
            "Sequências e Séries Infinitas",
            "Cálculo Vetorial",
            "Geometria Analítica",
            "Equações Diferenciais Ordinárias (EDOs)",
            "Transformada de Laplace",
            "Sistemas de Coordenadas Curvilíneas",
            "Teoria das Séries de Fourier",
            "Integrais de Linha e Superfície",
            "Equações Diferenciais Parciais (EDPs)",
            "Análise Complexa",
            "Transformada de Fourier",
            "Cálculo Numérico",
            "Aplicações em Engenharia de Computação"
        ],
        "ÁLG": ["Vetores", "Espaços Vetoriais", "Operações Vetoriais", "Independência Linear", "Base e Dimensão", "Transformações Lineares", "Matrizes", "Espaço Nulo e Espaço Coluna", "Sistemas de Equações Lineares", "Determinantes", "Autovalores e Autovetores", "Diagonalização", "Espaços Ortogonais", "Decomposição QR", "Álgebra Linear Numérica", "Outros", "AB1", "AB2", "Reavaliação"], 
        "CIDI":[
            "Álgebra Booleana",
            "Portas Lógicas",
            "Sistemas Numéricos",
            "Minimização de Circuitos",
            "Flip-Flops e Latches",
            "Registradores e Contadores",
            "Máquinas de Estados Finitos",
            "Memória Digital",
            "Arquitetura de Computadores",
            "Sistemas de Numeração Complementar",
            "Conversores Analógico-Digitais e Digitais-Analógicos",
            "Circuitos Combinacionais",
            "Memórias Cache",
            "Projeto de Circuitos Digitais",
            "Sistemas Integrados (Microcontroladores e FPGA)"
        ],
          "DESE":[
            "Diagramas de Circuitos",
            "Esquemas Elétricos",
            "Diagramas de Blocos",
            "Desenho Assistido por Computador (CAD)",
            "Diagramas de Fluxo",
            "Diagramas UML (Unified Modeling Language)",
            "Desenhos de Placas de Circuito Impresso (PCB)",
            "Desenho Técnico",
            "Modelagem 3D",
            "Documentação de Projetos",
            "Gráficos e Visualização de Dados",
            "Prototipagem Rápida",
            "Realidade Virtual e Aumentada",
            "Desenho de Interfaces de Usuário",
            "Representação Gráfica de Algoritmos"
        ],
          "LFAU":[
            "Alfabetos e Linguagens",
            "Gramáticas Formais",
            "Expressões Regulares",
            "Autômatos Finitos",
            "Autômatos de Pilha",
            "Máquinas de Turing",
            "Linguagens Recursivas",
            "Decidibilidade e Indecidibilidade",
            "Hierarquia de Chomsky",
            "Teorema de Pumping Lemma",
            "Máquinas de Estado Finito e Reconhecimento de Padrões",
            "Compiladores e Interpretadores",
            "Autômatos em Processamento de Linguagem Natural",
            "Aplicações em Computação",
            "Problemas NP-Completos"
        ],
          "PSOF":["Padrões de Projeto (Design Patterns)", "Arquiteturas de Software", "Desenvolvimento Orientado a Objetos (OOD)", "Testes de Software", "Gerenciamento de Configuração", "Documentação de Software", "Desenvolvimento Ágil", "Controle de Qualidade de Código", "Integração Contínua e Desdobramento Contínuo (CI/CD)", "Gestão de Equipe de Desenvolvimento", "Desenvolvimento de Interfaces de Programação de Aplicativos (APIs)", "Desenvolvimento de Aplicações Web e Móveis", "Segurança de Software", "Usabilidade e Experiência do Usuário (UX/UI)", "Empacotamento e Distribuição de Software", "Outros", "AB1", "AB2", "Reavaliação"],
          "FÍS2":[
            "Eletrostática",
            "Lei de Gauss",
            "Capacitores",
            "Corrente Elétrica",
            "Circuitos de Corrente Contínua",
            "Campos Magnéticos",
            "Lei de Ampère",
            "Indução Eletromagnética",
            "Circuitos de Corrente Alternada",
            "Ondas Eletromagnéticas",
            "Óptica Geométrica",
            "Óptica Física",
            "Termodinâmica",
            "Ondas Sonoras e Acústica",
            "Física Moderna"
        ],
          "C3": ["Limites e Continuidade", "Derivadas e Regras de derivação", "Aplicações de Derivada", "Teorema do Valor médio e Rolle", "Regra de L'Hôpital", "Aplicações", "Definição da Integral Definida", "Propriedades da Integral Definida", "Teorema Fundamental do Cálculo", "Regras de Integração", "Aplicações da Integral Definida", "Cálculo de Áreas e Volumes", "Integral Imprópria", "Séries e Sequências", "Equações Diferenciais", "Outros", "AB1", "AB2", "Reavaliação"],
          "MET": ["Formulação do Problema de Pesquisa", "Revisão da Literatura", "Definição de Objetivos e Hipóteses", "Seleção de Método de Pesquisa", "Coleta de Dados", "Amostragem", "Procedimentos de Coleta de Dados", "Análise de Dados", "Validade e Confiabilidade", "Interpretação dos Resultados", "Discussão", "Conclusões", "Limitações do Estudo", "Ética na Pesquisa", "Divulgação e Publicação", "Outros", "AB1", "AB2", "Reavaliação"],
          "SDG": ["Álgebra de Boole", "Portas Lógicas", "Sistemas de Numeração", "Circuitos Combinacionais", "Multiplexadores e Demultiplexadores", "Decodificadores e Codificadores", "Flip-Flops e Registradores", "Contadores e Temporizadores", "Sistemas de Lógica Programável", "Memória Digital", "Sistemas de Clock e Sincronização", "Projeto de Circuitos Digitais", "Arquitetura de Processadores", "Microcontroladores", "Sistemas Digitais em FPGA", "Outros", "AB1", "AB2", "Reavaliação"],
          "QUTE":[
            "Estrutura Atômica e Tabela Periódica",
            "Ligações Químicas",
            "Estequiometria",
            "Termoquímica",
            "Cinética Química",
            "Equilíbrio Químico",
            "Soluções e Concentrações",
            "Eletroquímica",
            "Química dos Materiais",
            "Polímeros",
            "Química dos Semicondutores",
            "Materiais Magnéticos",
            "Nanotecnologia",
            "Química Verde",
            "Química Analítica"
        ],
          "PROB": ["Probabilidade", "Variáveis Aleatórias", "Distribuição de Probabilidade", "Distribuições de Probabilidade Comuns", "Teorema do Limite Central", "Amostragem e Estimação", "Intervalos de Confiança", "Testes de Hipóteses", "Correlação e Regressão", "Estatísticas Descritivas", "Amostragem Aleatória Simples", "Experimentos Aleatórios", "Análise de Séries Temporais", "Estatística Bayesiana", "Aplicações em Ciência e Indústria", "Outros", "AB1", "AB2", "Reavaliação"], 
          "ENGS": [
            "Introdução à Engenharia de Software",
            "Processos de Desenvolvimento de Software",
            "Requisitos de Software",
            "Projeto de Software",
            "Implementação de Software",
            "Teste de Software",
            "Gerenciamento de Configuração de Software",
            "Qualidade de Software",
            "Engenharia de Software Orientada a Objetos",
            "Desenvolvimento Ágil",
            "Documentação de Software",
            "Gerenciamento de Projetos de Software",
            "Segurança de Software",
            "Manutenção e Evolução de Software",
            "Desenvolvimento de Software em Equipe"
        ],
          "CÁL4": [
            "Integrais Múltiplas",
            "Cálculo Vetorial",
            "Equações Diferenciais Ordinárias (EDOs)",
            "Equações Diferenciais Parciais (EDPs)",
            "Séries de Fourier",
            "Transformada de Fourier",
            "Análise Complexa",
            "Métodos Numéricos",
            "Equações Diferenciais Parciais em Duas Dimensões",
            "Modelagem Matemática",
            "Otimização",
            "Equações Diferenciais Estocásticas",
            "Aplicações em Engenharia da Computação",
            "Equações de Diferenças e Transformada Z",
            "Introdução à Teoria do Controle"
        ],
          "VACO": [
            "Números Complexos",
            "Funções Complexas",
            "Limites e Continuidade",
            "Derivadas Complexas",
            "Integração Complexa",
            "Teorema Residual",
            "Séries de Laurent e Singularidades",
            "Teorema de Liouville",
            "Teoria de Funções de Função Única",
            "Teorema de Resíduos em Aplicações",
            "Transformadas Integrais Complexas",
            "Aplicações em Engenharia e Física",
            "Funções Analíticas",
            "Teorema do Valor Médio de Poisson",
            "Teoria de Residência"
        ],
          "OAC": ["Arquitetura de Software", "Padrões de Projeto (Design Patterns)", "Arquitetura em Camadas", "Model-View-Controller (MVC)", "Microsserviços", "Arquitetura Orientada a Serviços (SOA)", "Arquitetura de Pipeline", "Padrões de Comunicação", "Injeção de Dependência (DI)", "Arquitetura Monolítica", "Arquitetura de Software Escalável", "Refatoração de Software", "Padrões de Arquitetura de Segurança", "Arquitetura Orientada a Eventos (EDA)", "Arquitetura de Software Distribuído", "Outros", "AB1", "AB2", "Reavaliação"],
          "FÍEX": [
            "Eletromagnetismo",
            "Ondas Eletromagnéticas",
            "Óptica Geométrica",
            "Óptica Física",
            "Relatividade Especial",
            "Mecânica Quântica",
            "Modelos Atômicos",
            "Física de Partículas",
            "Núcleos e Reações Nucleares",
            "Física dos Semicondutores",
            "Física da Matéria Condensada",
            "Energia Nuclear e Fusão",
            "Cosmologia",
            "Física Computacional",
            "Aplicações em Tecnologia"
        ],
          "PAA": ["Análise de Complexidade", "Algoritmos de Ordenação", "Algoritmos de Busca", "Algoritmos de Grafos", "Algoritmos de Programação Dinâmica", "Algoritmos de Fluxo Máximo", "Algoritmos de Geometria Computacional", "Algoritmos Greedy", "Algoritmos de Correspondência", "Algoritmos de Compressão de Dados", "Algoritmos de Aproximação", "Algoritmos em Cadeias de Caracteres", "Algoritmos Distribuídos", "Algoritmos Paralelos", "Problemas NP-Completos e Teoria da Complexidade", "Outros", "AB1", "AB2", "Reavaliação"],
          "CIEL": [
            "Lei de Ohm",
            "Análise de Circuitos DC",
            "Elementos de Circuitos",
            "Teoremas de Circuitos",
            "Análise de Circuitos AC",
            "Circuitos RLC",
            "Transformada de Laplace",
            "Sistemas Trifásicos",
            "Transientes e Resposta em Frequência",
            "Amplificadores Operacionais",
            "Teoria de Redes de Duas Portas",
            "Circuitos Digitais",
            "Análise de Circuitos em Estado Estacionário",
            "Aplicações em Eletrônica",
            "Simulação de Circuitos"
        ],
          "REDC": ["Topologias de Rede", "Protocolos de Rede", "Modelo OSI", "Arquiteturas de Rede", "Endereçamento IP", "Roteamento", "Switches e Roteadores", "Protocolos de Roteamento", "Redes Sem Fio", "Segurança de Rede", "Virtualização de Rede", "Redes de Área Local (LAN)", "Redes de Área Ampla (WAN)", "Redes de Data Center", "Monitoramento e Gerenciamento de Rede", "Outros", "AB1", "AB2", "Reavaliação"],
          "SISE": [
            "Introdução a Sinais e Sistemas",
            "Amostragem e Reconstrução",
            "Operações Básicas em Sinais",
            "Séries e Transformadas de Fourier",
            "Transformada de Laplace",
            "Análise de Sistemas LTI",
            "Convolução",
            "Amostragem de Sinais Contínuos",
            "Transformada Z",
            "Análise de Sinais no Domínio da Frequência",
            "Filtros Digitais",
            "Sistemas Discretos e Contínuos",
            "Análise de Sinais de Tempo Real",
            "Aplicações em Processamento de Áudio e Imagem",
            "Aplicações em Comunicações"
        ],
          "IA": ["Aprendizado de Máquina (Machine Learning)", "Redes Neurais Artificiais", "Processamento de Linguagem Natural (PLN)", "Visão Computacional", "Robótica Inteligente", "Agentes Inteligentes", "Aprendizado Profundo (Deep Learning)", "Algoritmos de IA", "Ética em IA", "IA e Medicina", "IA e Automóveis Autônomos", "IA na Indústria", "IA na Educação", "IA na Finança", "Futuro da IA", "Outros", "AB1", "AB2", "Reavaliação"],
          "SO": ["Funções Básicas do SO", "Multi tarefa", "Multi Processamento", "Interface com o Usuário", "Gerenciamento de Arquivos", "Segurança e Controle de Acesso", "Sistemas de Arquivos", "Gestão de Memória", "Sistemas de Arquivos Distribuídos", "Rede e Comunicação", "Inicialização do Sistema", "Desempenho e Otimização", "Manutenção e Atualizações", "Sistemas Operacionais Móveis", "Virtualização", "Outros", "AB1", "AB2", "Reavaliação"],
          "TG": ["Grafos e Subgrafos", "Grafos Dirigidos", "Grafos Não-dirigidos", "Grafos Ponderados", "Grafos Conexos e Desconexos", "Árvores e Florestas", "Grafos Bipartidos", "Caminhos e Ciclos", "Grafos Eulerianos e Hamiltonianos", "Matriz de Adjacência e Lista de Adjacência", "Algoritmos de Busca", "Algoritmos de Caminho Mínimo", "Algoritmos de Fluxo Máximo", "Grafos Planos", "Aplicações em Redes Sociais", "Outros", "AB1", "AB2", "Reavaliação"], 
          "PRCO": [
            "Sinais e Sistemas de Comunicação",
            "Modulação",
            "Demodulação",
            "Canais de Comunicação",
            "Codificação de Canal",
            "Multiplexação",
            "Espectro e Banda Passante",
            "Comunicação Digital",
            "Sistemas de Comunicação sem Fio",
            "Redes de Comunicação",
            "Comunicação de Dados",
            "Compressão de Dados",
            "Padrões de Comunicação",
            "Comunicação por Fibra Óptica",
            "Segurança de Comunicação"
        ],
          "ELET": [
            "Introdução à Eletrônica",
            "Componentes Eletrônicos",
            "Amplificadores",
            "Transistores",
            "Circuitos de Bias",
            "Amplificadores de Áudio",
            "Amplificadores de RF",
            "Osciladores",
            "Fontes de Alimentação",
            "Amplificadores de Instrumentação",
            "Eletrônica Digital",
            "Conversão Analógico-Digital",
            "Circuitos Integrados",
            "Amplificadores Operacionais",
            "Microeletrônica"
        ],
          "METN": [
            "Erro de Aritmética de Ponto Flutuante",
            "Métodos de Solução de Equações Não Lineares",
            "Interpolação e Aproximação",
            "Integração Numérica",
            "Diferenciação Numérica",
            "Resolução Numérica de Sistemas Lineares",
            "Método de Mínimos Quadrados",
            "Solução Numérica de Equações Diferenciais Ordinárias (EDOs)",
            "Equações Diferenciais Parciais (EDPs)",
            "Análise de Estabilidade e Convergência",
            "Aplicações em Engenharia da Computação",
            "Programação Numérica",
            "Software e Ferramentas Numéricas",
            "Análise de Erro e Incerteza",
            "Aplicações Práticas"
        ],
          "SICO": [
            "Introdução aos Sistemas de Controle",
            "Modelagem de Sistemas Dinâmicos",
            "Resposta no Domínio do Tempo",
            "Análise de Estabilidade",
            "Controladores e Compensadores",
            "Resposta em Frequência",
            "Técnicas de Projeto de Controladores",
            "Sistemas de Controle em Malha Aberta e Malha Fechada",
            "Controle de Sistemas de Tempo Contínuo e Tempo Discreto",
            "Controladores Digitais",
            "Análise de Resposta Transiente",
            "Controladores de Lugar das Raízes",
            "Controle de Sistemas Múltiplos",
            "Sistemas de Controle em Tempo Real",
            "Aplicações Práticas"
        ],
          "SICO2": [
            "Análise no Domínio do Espaço de Estados",
            "Projeto de Controladores em Espaço de Estados",
            "Realimentação de Estado Completo",
            "Análise de Resposta Transiente",
            "Projeto de Controladores Digitais",
            "Observabilidade e Controlabilidade",
            "Métodos de Projeto de Controladores Robustos",
            "Projeto de Controladores Não Lineares",
            "Controle Adaptativo",
            "Controle de Sistemas Multivariáveis",
            "Controle de Sistemas em Tempo Real",
            "Sistemas de Controle em Malha Fechada Não Lineares",
            "Controle Não Linear Avançado",
            "Controle de Sistemas MIMO (Múltiplas Entradas e Múltiplas Saídas)",
            "Aplicações Práticas"
        ],
        "CSÉ": ["Privacidade de Dados", "Ética na Inteligência Artificial (IA)", "Vigilância Digital", "Cibersegurança e Hacking Ético", "Responsabilidade em TI", "Desigualdades Digitais", "Neutralidade da Rede", "Ética em Big Data", "Propriedade Intelectual e Direitos Autorais", "Ética em Pesquisa em Computação", "Inteligência Artificial e Emprego", "Ética em Jogos e Entretenimento Digital", "Ética em Redes Sociais", "Acesso Universal à Tecnologia", "Ética no Desenvolvimento de Software", "Outros", "AB1", "AB2", "Reavaliação"],
        "EMPE": [
          "Conceitos Básicos de Empreendedorismo",
          "Desenvolvimento de Ideias",
          "Plano de Negócios",
          "Finanças para Empreendedores",
          "Marketing e Estratégia",
          "Gestão de Recursos Humanos",
          "Inovação e Tecnologia",
          "Aspectos Jurídicos e Regulatórios",
          "Financiamento e Captação de Recursos",
          "Networking e Desenvolvimento de Parcerias",
          "Mentoria e Aconselhamento",
          "Gerenciamento de Riscos",
          "Ética nos Negócios",
          "Estratégias de Crescimento",
          "Casos de Estudo e Experiência Prática"
      ],
          "FETR": [
            "Transferência de Calor",
            "Transferência de Massa",
            "Mecânica dos Fluidos",
            "Escoamento de Fluidos",
            "Troca de Calor em Fluidos",
            "Máquinas Térmicas",
            "Fenômenos de Transporte em Computação",
            "Transferência de Calor em Dispositivos Eletrônicos",
            "Transferência de Massa em Processamento de Sinais",
            "Aplicações em Engenharia da Computação",
            "Experimentação e Laboratório",
            "Aplicações na Indústria",
            "Aplicações na Energia",
            "Sustentabilidade e Meio Ambiente",
            "Aplicações de Simulação"
        ],
          "BD": ["Modelo de Dados", "SQL (Structured Query Language)", "Sistemas de Gerenciamento de Banco de Dados (DBMS)", "Normalização", "Chave Primária e Chave Estrangeira", "Índices", "Transações", "NoSQL Databases", "Replicação de Dados", "Sharding", "Banco de Dados em Memória", "Backup e Recuperação", "Segurança de Banco de Dados", "Modelagem de Dados", "Big Data", "Outros", "AB1", "AB2", "Reavaliação"],
          "ND": ["Regras e Leis", "Justiça", "Igualdade perante a Lei", "Presunção de Inocência", "Devido Processo Legal", "Direitos Humanos", "Responsabilidade Civil e Criminal", "Contratos", "Propriedade", "Jurisprudência", "Órgãos Jurídicos", "Advogados e Juízes", "Princípio do Contraditório", "Prescrição", "Legislação e Poder Legislativo", "Outros", "AB1", "AB2", "Reavaliação"],
          "MICR": ["Introdução a Microcontroladores", "Arquitetura de Microcontroladores", "Programação de Microcontroladores", "Periféricos de Microcontroladores", "Comunicação Serial", "Interrupções e Temporização", "Memória de Programa e Dados", "Conversão Analógico-Digital (ADC)", "PWM (Modulação por largura de pulso)", "Interface com Sensores", "Sistemas de Controle Embarcados", "Microcontroladores em Eletrônica de Consumo", "Aplicações Automotivas", "Microcontroladores em Dispositivos Médicos", "Desenvolvimento de Projetos com Microcontroladores", "Outros", "AB1", "AB2", "Reavaliação"],
          "INEL": [
            "Sensores e Transdutores",
            "Amplificação de Sinais",
            "Conversão Analógico-Digital (ADC)",
            "Conversão Digital-Analógica (DAC)",
            "Filtros e Filtragem",
            "Teoria de Erros de Medição",
            "Sistemas de Aquisição de Dados",
            "Interfaces e Comunicação",
            "Telemetria e Comunicação sem Fio",
            "Automação e Controle",
            "Instrumentação Virtual",
            "Calibração de Instrumentos",
            "Aplicações Práticas",
            "Segurança em Instrumentação",
            "Projeto de Sistemas de Medição"
        ],
          "PDIS": [
            "Sinais e Sistemas",
            "Amostragem e Reconstrução de Sinais",
            "Transformada de Fourier",
            "Transformada Z",
            "Filtros Digitais",
            "Transformada de Laplace Discreta",
            "Processamento de Sinais de Voz",
            "Processamento de Sinais de Imagem",
            "Compressão de Sinais",
            "Análise Espectral",
            "Processamento de Sinais Biomédicos",
            "Aplicações em Telecomunicações",
            "Processamento de Sinais Multimídia",
            "Processamento de Sinais em Tempo Real",
            "Aplicações Práticas"
        ],
        "CG": ["Rasterização e Vetorização", "Modelagem 3D", "Renderização", "Texturização", "Animação", "Realidade Virtual (VR) e Realidade Aumentada (AR)", "Gráficos de Jogos", "Simulação", "Visualização de Dados", "Edição de Imagens", "Técnicas de Pintura Digital", "Computação Gráfica em Medicina", "Computação Gráfica em Design Industrial", "Computação Gráfica em Animação por Computador (CGI)", "Tendências em Computação Gráfica", "Outros", "AB1", "AB2", "Reavaliação"],
        "SE": ["Introdução a Sistemas Embarcados", "Microcontroladores", "Arquitetura de Computadores Embarcados", "Programação de Baixo Nível", "Sistemas Operacionais Embarcados", "Periféricos e Interfaces", "Comunicação sem Fio", "Economia de Energia", "Desenvolvimento de Firmware", "Segurança em Sistemas Embarcados", "Depuração e Testes", "Design de Sistemas Embarcados", "Sistemas Embarcados em Tempo Real", "Sistemas Embarcados em Automóveis", "Tendências em Sistemas Embarcados", "Outros", "AB1", "AB2", "Reavaliação"],
          "SDI": ["Álgebra de Boole", "Portas Lógicas", "Sistemas de Numeração", "Circuitos Combinacionais", "Multiplexadores e Demultiplexadores", "Decodificadores e Codificadores", "Flip-Flops e Registradores", "Contadores e Temporizadores", "Sistemas de Lógica Programável", "Memória Digital", "Sistemas de Clock e Sincronização", "Projeto de Circuitos Digitais", "Arquitetura de Processadores", "Microcontroladores", "Sistemas Digitais em FPGA", "Outros", "AB1", "AB2", "Reavaliação"],
          "AUIN": [
            "Sensores e Atuadores",
            "Controle de Processos",
            "PLCs (Controladores Lógicos Programáveis)",
            "Redes Industriais",
            "Sistemas SCADA (Supervisory Control and Data Acquisition)",
            "Robótica Industrial",
            "Instrumentação Industrial",
            "Sistemas de Visão",
            "Integração de Sistemas",
            "Segurança Industrial",
            "Manutenção Preditiva",
            "Eficiência Energética",
            "Indústria 4.0 e IIoT (Internet Industrial das Coisas)",
            "Padrões e Normas Industriais",
            "Aplicações Específicas"
        ],
          "ROBÓ": [
            "Cinemática de Robôs",
            "Dinâmica de Robôs",
            "Sensores em Robótica",
            "Atuadores em Robótica",
            "Programação de Robôs",
            "Visão Computacional em Robótica",
            "Aprendizado de Máquina em Robótica",
            "Controle de Robôs Móveis",
            "Robótica Colaborativa",
            "Robótica Autônoma",
            "Robótica Industrial",
            "Robótica Médica",
            "Robótica de Serviço",
            "Ética e Robótica",
            "Aplicações Práticas"
        ],
          "MÉSO": [
            "Introdução à Mecânica dos Sólidos",
            "Tensão e Deformação",
            "Lei de Hooke",
            "Cisalhamento e Flexão",
            "Torque e Tensão de Torção",
            "Critérios de Falha",
            "Análise de Vigas e Pórticos",
            "Deflexões e Deformações Axiais",
            "Elementos Finitos",
            "Análise de Tensões Termomecânicas",
            "Análise de Fadiga",
            "Comportamento Não Linear",
            "Análise de Tensões Tridimensionais",
            "Elementos de Máquina e Projeto de Estruturas",
            "Aplicações Práticas"
        ],
          "CLP": ["Introdução às Linguagens de Programação", "Sintaxe e Semântica", "Tipos de Dados", "Variáveis e Constantes", "Estruturas de Controle", "Funções e Procedimentos", "Escopo de Variáveis", "Recursão", "Programação Orientada a Objetos", "Manipulação de Exceções", "Programação Funcional", "Paradigmas de Linguagens de Programação", "Compilação vs. Interpretação", "Gerenciamento de Memória", "Linguagens de Programação Populares", "Outros", "AB1", "AB2", "Reavaliação"],
          "SEVE": [
            "Modelagem de Eventos Discretos",
            "Simulação de Sistemas de Eventos Discretos",
            "Redes de Petri",
            "Lógica de Temporal",
            "Controle de Sistemas de Eventos Discretos",
            "Análise de Desempenho",
            "Modelos de Filas",
            "Aplicações Industriais",
            "Protocolos de Comunicação",
            "Aplicações em Transporte e Logística",
            "Engenharia de Tráfego",
            "Aplicações em Saúde",
            "Segurança e Confiabilidade",
            "Aplicações em Jogos e Entretenimento",
            "Aplicações em Sistemas Distribuídos"
        ],
          "COMPI": ["Fases do Compilador", "Análise Léxica", "Análise Sintática", "Análise Semântica", "Tabela de Símbolos", "Geração de Código Intermediário", "Otimização de Código", "Geração de Código de Máquina", "Compiladores vs. Interpretadores", "Linguagens de Programação", "Bibliotecas e APIs", "Depuração", "Compiladores Just-in-Time (JIT)", "Compiladores de Linguagem de Montagem", "Compiladores de Alto Desempenho", "Outros", "AB1", "AB2", "Reavaliação"],
          "PRLP": [
            "Programação Procedural",
            "Programação Orientada a Objetos (POO)",
            "Programação Funcional",
            "Programação Declarativa",
            "Programação Lógica",
            "Programação Estruturada",
            "Programação Orientada a Eventos",
            "Programação Concorrente e Paralela",
            "Programação Genérica",
            "Programação Orientada a Aspectos (AOP)",
            "Programação Reativa",
            "Programação Baseada em Regras",
            "Programação Orientada a Serviços (SOA - Service-Oriented Architecture)",
            "Programação Orientada a Protocolo (gRPC, REST)",
            "Programação Baseada em Componentes"
        ],
          "GP": ["Introdução à Ciência de Dados", "Coleta de Dados", "Limpeza e Pré-processamento de Dados", "Análise Exploratória de Dados (EDA)", "Estatística", "Aprendizado de Máquina (Machine Learning)", "Big Data", "Processamento de Linguagem Natural (NLP)", "Aprendizado Profundo (Deep Learning)", "Mineração de Dados", "Visualização de Dados", "Modelagem Preditiva", "Ética e Privacidade de Dados", "Deploy de Modelos", "Casos de Uso em Ciência de Dados", "Outros", "AB1", "AB2", "Reavaliação"],
          "LAPR": [
            "Exercícios de Sintaxe",
            "Estruturas de Dados Básicas",
            "Algoritmos e Resolução de Problemas",
            "Projeto de Aplicações Simples",
            "Uso de Bibliotecas e Frameworks",
            "Programação Orientada a Objetos (POO)",
            "Tratamento de Erros",
            "Programação Multithread e Concorrência",
            "Interfaces Gráficas de Usuário (GUIs)",
            "Programação de Redes",
            "Teste e Depuração",
            "Segurança de Software",
            "Desenvolvimento Colaborativo",
            "Documentação e Relatórios",
            "Competições de Programação"
        ],
          "FLIB": [
            "História e Evolução da Libras",
            "Estrutura Linguística",
            "Alfabeto Manual",
            "Sinais Básicos",
            "Expressões Faciais e Movimentos Corporais",
            "Gramática de Libras",
            "Compreensão Contextual",
            "Variações Regionais",
            "Cultura Surda",
            "Acessibilidade e Inclusão",
            "Interpretação em Libras",
            "Legislação e Direitos",
            "Tecnologia e Recursos de Apoio",
            "Educação em Libras",
            "Desafios e Barreiras"
        ],
          "DBON": [
            "Introdução às Ontologias",
            "Linguagens de Ontologia",
            "Modelagem Ontológica",
            "Ontologias e a Web Semântica",
            "Repositórios de Ontologias",
            "Raciocínio com Ontologias",
            "Alinhamento de Ontologias",
            "Aplicações de Ontologias",
            "Engenharia de Conhecimento",
            "Ontologias e Aprendizado de Máquina",
            "Padrões e Ferramentas Ontológicas",
            "Avaliação de Ontologias",
            "Desenvolvimento de Aplicações Baseadas em Ontologias",
            "Ontologias e Inteligência Artificial",
            "Ética e Privacidade em Ontologias"
        ],
          "TECÉ": [
            "Circuitos Elétricos de Alta Frequência",
            "Eletrônica de Potência",
            "Circuitos Integrados Analógicos",
            "Dispositivos Semicondutores de Potência",
            "Circuitos Resonantes e Osciladores",
            "Circuitos Bioeletrônicos",
            "Circuitos em Nanoescala",
            "Circuitos para Comunicações Ópticas",
            "Projeto de Circuitos Integrados",
            "Circuitos para Eletrônica de Consumo",
            "Circuitos para Automação e Controle Industrial",
            "Circuitos para Eletrônica Embarcada",
            "Circuitos para Telecomunicações",
            "Circuitos de RF (Radiofrequência)",
            "Circuitos para Sistemas de Controle de Potência"
        ],
          "LAED": [
            "Implementação de Estruturas de Dados",
            "Manipulação de Dados",
            "Análise de Complexidade",
            "Ordenação e Pesquisa",
            "Uso de Bibliotecas",
            "Depuração e Teste",
            "Análise de Desempenho",
            "Estruturas de Dados Avançadas",
            "Aplicações Práticas",
            "Visualização de Estruturas de Dados",
            "Projetos de Algoritmos",
            "Colaboração em Equipe",
            "Documentação e Relatórios",
            "Desafios de Programação",
            "Práticas"
        ],
          "LAEL": [
            "Montagem de Circuitos Eletrônicos",
            "Instrumentação",
            "Leis de Kirchhoff e Análise de Circuitos",
            "Amplificadores",
            "Filtros Eletrônicos",
            "Circuitos Digitais",
            "Fontes de Alimentação",
            "Amostragem e Digitalização",
            "Comunicações Eletrônicas",
            "Robótica e Controle",
            "Projeto de Projetos de Eletrônica",
            "Segurança e Normas",
            "Documentação e Relatórios",
            "Simulação e Prototipagem",
            "Integração de Microcontroladores"
        ],
          "LACE": [
            "Montagem de Circuitos",
            "Medições Elétricas",
            "Análise de Circuitos",
            "Amplificadores",
            "Circuitos Digitais",
            "Fontes de Alimentação",
            "Amostragem e Digitalização",
            "Osciladores e Temporizadores",
            "Comunicação de Dados",
            "Projeto de Projetos de Eletrônica",
            "Resolução de Problemas e Depuração",
            "Segurança em Eletrônica",
            "Documentação e Relatórios",
            "Integração com Software",
            "Práticas"
        ],
          "REPE": [
            "Elementos Fundamentais",
            "Modelagem de Sistemas",
            "Semântica",
            "Propriedades de Sistemas",
            "Redes de Petri Coloridas",
            "Análise de Desempenho",
            "Verificação de Software",
            "Controle de Sistemas",
            "Redes de Petri Temporizadas",
            "Ferramentas de Modelagem",
            "Aplicações em Protocolos de Comunicação",
            "Aplicações em Sistemas Embarcados",
            "Aplicações em Sistemas de Produção",
            "Aplicações em Sistemas de Transporte",
            "Aplicações em Biologia e Química"
        ],
          "ITIN": [
            "Conceitos Básicos de Informação",
            "Entropia",
            "Códigos de Huffman",
            "Teoria da Codificação",
            "Canal de Comunicação",
            "Taxa de Transmissão e Eficiência de Codificação",
            "Teorema da Codificação de Canal",
            "Compressão de Dados",
            "Teoria da Informação e Criptografia",
            "Aplicações Práticas",
            "Teoria da Informação e Machine Learning",
            "Teoria da Informação e Redes de Computadores",
            "Teoria da Informação Quântica",
            "Teoria da Informação e Redes Sociais",
            "Aplicações em Inteligência Artificial"
        ],
          "IA2": [
            "Aprendizado Profundo (Deep Learning)",
            "Redes Neurais Convolucionais (CNNs)",
            "Redes Neurais Recorrentes (RNNs)",
            "Redes Generativas Adversariais (GANs)",
            "Processamento de Linguagem Natural Avançado",
            "Reforço (Reinforcement Learning)",
            "Aprendizado Profundo em Jogos",
            "Ética em IA:",
            "IA Explicável e Interpretabilidade",
            "Aprendizado Federado e Privacidade em IA",
            "Robótica Autônoma",
            "Sistemas Multiagentes",
            "IA e Saúde",
            "IA e Visão Computacional Avançada",
            "IA em Empresas e Aplicações Empresariais"
        ],
          "DCQC": [
            "Introdução ao Qt",
            "Configuração do Ambiente de Desenvolvimento",
            "Conceitos Básicos do Qt",
            "Desenvolvimento de Interfaces Gráficas de Usuário (GUI)",
            "Widgets Qt",
            "Tratamento de Eventos e Interação do Usuário",
            "Gerenciamento de Layout",
            "Acesso a Dados e Comunicação",
            "Personalização de Estilos e Temas",
            "Internacionalização e Localização",
            "Gráficos e Renderização 2D",
            "Desenvolvimento Multiplataforma",
            "Testes e Depuração",
            "Integração com Outras Tecnologias",
            "Desenvolvimento de Aplicativos Móveis"
        ],
        }
    },
};
  
export const corPorCursoPeriodo = {
    'CC': {
        '1º Período': { backgroundColor: '#FF7474', color: 'white' },
        '2º Período': { backgroundColor: '#8979FD', color: 'white' },
        '3º Período': { backgroundColor: '#F27FEF', color: 'white' },
        '4º Período': { backgroundColor: '#87E4FE', color: 'white' },
        '5º Período': { backgroundColor: '#FCD878', color: 'white' },
        '6º Período': { backgroundColor: '#90FCDF', color: 'white' },
        '7º Período': { backgroundColor: '#E9FD7A', color: 'white' },
        'Computação Visual': { backgroundColor: '#7394FD', color: 'white' },
        'Sistemas Inteligentes': { backgroundColor: '#F8B076', color: 'white' },
        'Sistemas de Computação': { backgroundColor: '#F27ED6', color: 'white' },
        'Sistemas de Informação': { backgroundColor: '#F24430', color: 'white' },
    },
    'EC': {
        '1º Período': { backgroundColor: '#FF7474', color: 'white' },
        '2º Período': { backgroundColor: '#8979FD', color: 'white' },
        '3º Período': { backgroundColor: '#F27FEF', color: 'white' },
        '4º Período': { backgroundColor: '#87E4FE', color: 'white' },
        '5º Período': { backgroundColor: '#FCD878', color: 'white' },
        '6º Período': { backgroundColor: '#90FCDF', color: 'white' },
        '7º Período': { backgroundColor: '#E9FD7A', color: 'white' },
        '8º Período': { backgroundColor: '#7394FD', color: 'white' },
        'Eletivas': { backgroundColor: '#F8B076', color: 'white' },
        'Eletivas 2': { backgroundColor: '#F8B076', color: 'white' },
    },
};
  
export const OpcaoDisciplina = styled.option`
  background-color: #343434;
  width: 80px;
  height: 50px;
  padding-top: 13px;
  margin-right: 5px;
  font-weight: bold;
  border-radius: 13px;
  text-align: center;
  float: left;

  ${(props) =>
    corPorCursoPeriodo[props.curso] &&
    corPorCursoPeriodo[props.curso][props.periodo] &&
    `
      background-color: ${corPorCursoPeriodo[props.curso][props.periodo].backgroundColor};
      color: ${corPorCursoPeriodo[props.curso][props.periodo].color};
    `}

  ${(props) =>
    props.curso === 'CC' &&
    props.selecionado &&
    `
      background-color: #FFF;
      color: black;
    `}
  ${(props) =>
    props.curso === 'EC' &&
    props.selecionado &&
    `
    background-color: #FFF;
    color: black;
    `}
`;